[tool.isort]
# Match what Black will do:
multi_line_output = 3
line_length = 88

skip = [
    "migrations",
    "node_modules",
]


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--doctest-modules"

env = [
    "USE_TEST_DB=true"
]

# pytest-django
DJANGO_SETTINGS_MODULE = "CreeDictionary.CreeDictionary.settings"

django_find_project = false
python_paths = "."
