# copy pasted. you can change it
env:
  browser: true
  es6: true
  node: true
  webextensions: true
  jquery: true
  mocha: true
globals:
  XRegExp: true
  # Cypress/Chai globals
  Cypress: true
  cy: true
  expect: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2016
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - never
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
  no-console: "warn"
