version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DEBUG=False
    volumes:
      - "./db.sqlite3:/app/CreeDictionary/db.sqlite3"
      - "./.env:/app/.env"
    ports:
      # gunaha was using 8000, so let's use 8001, yay!
      - 8001:8000
