# Production docker-compose for itwewina.

version: "3"

services:
  itwewina:
    restart: always
    image: ghcr.io/ualbertaaltlab/itwewina.altlab.app:latest
    ports:
      # Why port 8001?
      # See: https://github.com/UAlbertaALTLab/deploy.altlab.dev/blob/master/docs/application-registry.tsv
      - 8001:8000
      # Note: If you want to run the Cypress tests on the staging container, use the
      # following:
      #
      # CYPRESS_BASE_URL=https://localhost:8001 cypress rund
      #
      # See: https://docs.cypress.io/guides/guides/environment-variables.html#We-can-move-this-into-a-Cypress-environment-variable

      # uWSGI stats can be accessed here on localhost:
      - "9191:9191"
    volumes:
      - "./.env:/app/.env"
      - "/data_local/application-data/itwewina/db/:/app/CreeDictionary/db/"
      - "/data_local/application-data/itwewina/search-quality/:/app/CreeDictionary/search_quality/sample_results/"
