version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - "./db.sqlite3:/app/CreeDictionary/db.sqlite3"
    ports:
      # gunaha was using 8000, so let's use 8001, yay!
      - 8001:8000
