# Base docker-compose for itwewina.
#
# NOTE!!!!!!!!!
# This docker-compose file is useless standalone. You **MUST** combine it with
# either ./production.yml or ./staging.yml.
#
# Why? Because docker-compose merges the `ports` setting in a sad way :(
#
# To use in experiment before running in production, use the following:
#
#     docker-compose -f docker-compose.yml -f staging.yml
#
# To use in production, use the following:
#
#     docker-compose -f docker-compose.yml -f production.yml
#
# See: https://docs.docker.com/compose/extends/#multiple-compose-files

version: "3"

services:
  itwewina:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - "./.env:/app/.env"
