name: Reformats various files

on:
  push:
    branches: [ master ]

jobs:
  # NOTE: Do all jobs SEQUENTIALLY to avoid merges

  reformat-altlabel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Reformat
      run: ./libexec/altlabel_utils.py format
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.3.0
      with:
        commit_message: "🤖🧹 reformat crk.altlabel [skip travis]"

  reformat-python:
    runs-on: ubuntu-latest
    # Ensure this is run **sequentially**
    needs: reformat-altlabel
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: "pip install black"
    - name: Reformat Python
      run: |
        black .
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.3.0
      with:
        commit_message: "🤖🧹 reformat Python files [skip travis]"

  reformat-javascript:
    runs-on: ubuntu-latest
    # Ensure this is run **sequentially**
    needs: reformat-python
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: '12'
    - name: Install dependencies
      run: npm ci
    - name: Reformat JavaScript
      run: npx eslint --fix src/ cypress/
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.3.0
      with:
        commit_message: "🤖🧹 reformat JavaScript files [skip travis]"
