name: Reformat crk.altlabel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  reformat:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Reformat
      run: ./libexec/altlabel_utils.py format
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.3.0
      with:
        commit_message: "🤖🧹 reformat crk.altlabel [skip travis]"
