# Based on: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 🐍 Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install system dependencies
      run: apt install hfst
    - name: ☤ Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: pipenv install --dev
    - name: Run unit tests
      run: pipenv run test --cov=CreeDictionary
