# Based on: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# Note: to skip both travis and github actions, add both [skip ci/travis] and [skip actions] to your commit message

name: Test and deploy
on: [push]

jobs:
  unit-test:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip actions]')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 🐍 Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: 🖥 Install system dependencies
      run: sudo apt-get install -y hfst
    - name: ☤ Install pipenv
      run: python3 -m pip install pipenv
    - name: 📥 Install dependencies
      run: |
        pipenv install --dev
        # Install pytest plugin to show failed tests on the web
        pipenv run pip install pytest-github-actions-annotate-failures
    - name: 🩺 Run unit tests
      env:
        DEBUG: "True"
        USE_TEST_DB: "True"
      run: pipenv run test -v --cov=CreeDictionary

# This syncs up API/schema.py to our @altlab/types package
# If there is an update to the type output (index.ts), but the version number is untouched. This
# will fail. Because developer needs to choose which version to bump.
  type-package-check:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip actions]')"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🐍 Set up Python 3.6
      uses: actions/setup-python@v2
      with: # python-typing-to-typescript requires python 3.9
        python-version: 3.9

    - name: Setup Node 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: "❓ Check if types changed"
      run: |
        # get published version and the conversion tool we are using
        npm install -g @altlab/types python-typing-to-typescript

        # convert our current schema.py to index.ts
        pttts CreeDictionary/API/schema.py types/index.ts

        # assert version change if the current types are different
        python3 .github/workflows/check_types_version_bump.py ./types $(npm root -g)/@altlab/types